# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSmokeside():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_smokeside(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1295, 687)
    self.driver.find_element(By.CSS_SELECTOR, ".header-logo img").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "nopad").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    self.driver.find_element(By.CSS_SELECTOR, ".header-top").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-top").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-top").click()
    assert self.driver.title == "Teton Idaho CoC"
    elements = self.driver.find_elements(By.ID, "nopad")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".join-wizard-main")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Join").click()
    self.driver.find_element(By.LINK_TEXT, "Directory").click()
    self.driver.find_element(By.ID, "directory-grid").click()
    self.driver.find_element(By.ID, "directory-list").click()
    self.driver.find_element(By.LINK_TEXT, "Join").click()
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "fname").send_keys("samuel")
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.NAME, "fname").send_keys("samuel")
    self.driver.find_element(By.NAME, "lname").click()
    self.driver.find_element(By.NAME, "lname").send_keys("Evbosaru")
    self.driver.find_element(By.CSS_SELECTOR, ".myinput:nth-child(3)").click()
    self.driver.find_element(By.NAME, "lname").click()
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.CSS_SELECTOR, ".myinput:nth-child(2)").click()
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "fname").send_keys(Keys.DOWN)
    elements = self.driver.find_elements(By.NAME, "submit")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "bizname").send_keys("sambh")
    self.driver.find_element(By.NAME, "biztitle").click()
    self.driver.find_element(By.NAME, "biztitle").send_keys("ceo")
    elements = self.driver.find_elements(By.NAME, "submit")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "submit").click()
    elements = self.driver.find_elements(By.NAME, "email")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Admin").click()
    self.driver.find_element(By.ID, "username").click()
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("fdrr")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("hhjk")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".errorMessage")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".errorMessage")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".errorMessage")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".errorMessage")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "fieldset").click()
    self.driver.find_element(By.CSS_SELECTOR, "fieldset").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "fieldset")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
